name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: check build
        run: cargo check --all --bins --examples --tests --verbose

      - name: tests
        timeout-minutes: 40
        run: cargo test --all --verbose --no-fail-fast -- --nocapture

  publish:
    name: Publish Package
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: login
        env:
          SUPER_SECRET: ${{ secrets.CARGO_TOKEN }}
        run: cargo login "$SUPER_SECRET"
        shell: bash

      - name: publish
        run: cargo publish

